DROP TABLE IF EXISTS "ingredients" CASCADE;

DROP TABLE IF EXISTS "categories" CASCADE;

DROP TABLE IF EXISTS "recipes" CASCADE;

DROP TABLE IF EXISTS "recipe_ingredients" CASCADE;

DROP TABLE IF EXISTS "recipe_categories" CASCADE;

DROP TABLE IF EXISTS "recipe_images" CASCADE;